services:
  kafka:
    image: apache/kafka:latest 
    expose:
      - "9092"
    ports:
      - "9092:9092"  
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9091, CONTROLLER://localhost:9093, INTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092, PLAINTEXT://localhost:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOl_MAP: CONTROLLER:PLAINTEXT, PLAINTEXT:PLAINTEXT, INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
  
  input:
    build: 
      context: ./input
    depends_on:
      - kafka
      
  processor:
    build: 
      context: ./processor
    depends_on:
      - kafka
  
  output:
    build: 
      context: ./output
    depends_on:
      - kafka
    volumes:
      - ./data/output:/app/output_data

