services:
  producer:
    build:
      context: ./producer
    depends_on:
      - input
  input:
    build: 
      context: ./input
    ports:
      - "5000:5000"
    depends_on:
      - processor
  processor:
    build: 
      context: ./processor
    ports:
      - "5001:5001"
    depends_on:
      - output
  output:
    build: 
      context: ./output
    ports:
      - "5002:5002"
    volumes:
      - ./data/output:/app/output_data
